name: SBOM Generator (GitHub)

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            echo "Installing from requirements.txt"
            pip install --upgrade pip
            pip install -r requirements.txt
          elif [ -f setup.py ]; then
            echo "Installing from setup.py"
            pip install --upgrade pip
            pip install .
          elif [ -f pyproject.toml ]; then
            echo "Installing from pyproject.toml"
            pip install --upgrade pip
            pip install build
            python -m build
            pip install dist/*.whl
          else
            echo "No known dependency file found (requirements.txt, setup.py, pyproject.toml)"
            exit 1
          fi
          
      # - name: Generate JSON SBOM
      #   uses: CycloneDX/gh-python-generate-sbom@v2
      - name: Install cyclonedx-bom
        run: pip install cyclonedx-bom
      
      - name: Generate SBOM
        run: |
          if [ -f requirements.txt ]; then
            cyclonedx-py requirements -i requirements.txt -o sbom.json
          elif [ -f poetry.lock ]; then
            cyclonedx-py poetry -i poetry.lock -o sbom.json
          elif [ -f Pipfile.lock ]; then
            cyclonedx-py pipenv -i Pipfile.lock -o sbom.json
          else
            cyclonedx-py environment -o sbom.json
          fi
      - name: Upload SBOM files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-files
          path: |
            hsbom.cdx.json
          
      - name: Commit SBOM to Repository
        run: |
          git config --local user.email "hayasam@najah.edu"
          git config --local user.name "hayasam"
          git add hsbom.cdx.json
          git commit -m "Add SBOM"
      # - name: Install Syft
      #   run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      # - name: Generate SBOM
      #   run: syft dir:. --source-name myproject --source-version 1.0.0 -o cyclonedx-json > sbom.github.json


      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: sbom-github
      #     path: sbom.github.json
